name: flutter_envied_injectable
description: Better .env integration in multiple environments with ENVied, GetIt and injectable.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-53.0.dev <4.0.0'

dependencies:
  envied: ^0.3.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  injectable: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  envied_generator: ^0.3.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
